// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDre4hKRpLByPcUV4ccAFbS9ccHM-1jLc',
    appId: '1:633288899758:web:92046f916b830beaabc13f',
    messagingSenderId: '633288899758',
    projectId: 'neurovault-app',
    authDomain: 'neurovault-app.firebaseapp.com',
    storageBucket: 'neurovault-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIuocWjzIXbIijoR4ZsSPT_merBPjuy4A',
    appId: '1:633288899758:android:77fc22add0eab590abc13f',
    messagingSenderId: '633288899758',
    projectId: 'neurovault-app',
    storageBucket: 'neurovault-app.firebasestorage.app',
  );

}